language: java
script: gradle build jacocoTestReport

jdk:
  - oraclejdk8

before_install:
  - sudo pip install codecov
after_success:
  - codecov
  - bash <(curl -s https://raw.githubusercontent.com/TouK/sputnik/saas/sputnik-ci.sh)
